/* Final content completion layer — public review build. */
const finalCourseGroups=[
  {id:'paddle',title:'PADDLE',meta:'8 HOURS · 1 DAY',aud:'ADULT / PARENT + CHILD',steps:'DESIGN → CUTTING → SHAPING → SANDING → WATERPROOFING',image:'archive-boat-making.jpg'},
  {id:'stitch-canoe',title:'STITCH CANOE',meta:'14 HOURS · 2 DAYS',aud:'ADULT / PARENT + CHILD',steps:'DESIGN → CUTTING → STITCHING → RESIN → SANDING → VARNISH',image:'archive-boat-making.jpg'},
  {id:'stripe-canoe',title:'STRIPE CANOE',meta:'120 HOURS · 12 DAYS',aud:'ADULT',steps:'DESIGN → CUTTING → JOINERY → STEAM BENDING → RESIN → SANDING → VARNISH',image:'archive-boat-water.jpg',feature:true},
  {id:'openbike',title:'OPENBIKE',meta:'DESIGN · CNC · LASER · 3D PRINTING',aud:'ADULT / PARENT + CHILD',steps:'',image:'archive-openbike.jpg'},
  {id:'digital-furniture',title:'DIGITAL FURNITURE',meta:'20 DESIGNS',aud:'ROCKET STOOL · SWISH · NEUBAU',steps:'',image:'asset-team-work.png'},
  {id:'digital-joinery',title:'常识班',meta:'20 LESSONS',aud:'DIGITAL JOINERY · ELECTRICITY / POWER · WATER SYSTEM · ARCHITECTURE · PAINTING · CEMENT · HARDWARE WELDING',steps:'',image:'archive-digital-shop-making.jpg'},
  {id:'wilderness',title:'荒野建造大师班',meta:'15 DAYS · HISTORICAL FORMAT',aud:'ADULT / PARENT + CHILD',steps:'',image:'archive-xinjiang-process.jpg'},
  {id:'future-architects',title:'未来建筑师',meta:'AGE 8–14 · BILINGUAL',aud:'WINTER / SUMMER · HISTORICAL FORMAT',steps:'',image:'asset-summer-camp.png'}
];

edBuilding=function(){return `<article class="ed-page final-building">${edLead('03 / BUILDING',{zh:'建造体验',en:'BUILDING'},{zh:'选择当前开放报名的建造内容。',en:'Choose a current building programme open for enrollment.'})}<section class="final-building-intro">${filePic('asset-building-process.png',{zh:'制作与建造过程',en:'Making and building process'},'ed-wide')}<div><strong>LEARNING + MAKING + BUILDING PRACTICE</strong><p>${tr('每个入口直接进入对应课程详情；具体日期只在确认后进入 WHAT’S ON。','Each entry opens its course detail. Dates appear in WHAT’S ON only after confirmation.')}</p></div></section><section class="final-course-index">${finalCourseGroups.map((c,i)=>`<a href="#/courses/${c.id}" class="${c.feature?'is-feature':''}">${filePic(c.image,{zh:c.title,en:c.title})}<div><small>${String(i+1).padStart(2,'0')} / OPEN FOR ENROLLMENT</small><h2>${esc(zh?c.title:({'常识班':'Common Knowledge','荒野建造大师班':'Wilderness Building Masterclass','未来建筑师':'Future Architects'}[c.title]||c.title))}</h2><strong>${c.meta}</strong><p>${c.aud}</p>${c.steps?`<span>${c.steps}</span>`:''}<b>${tr('查看课程','VIEW COURSE')} ↗</b></div></a>`).join('')}</section></article>`};

const finalCourseBase=edCourse;
edCourse=function(id){const html=finalCourseBase(id);if(!html)return null;const course=finalCourseGroups.find(c=>c.id===id);const add=id==='stitch-canoe'?`<section class="final-course-stay"><small>STAY AT PFS</small><h2>MAKE IT A BUILD WEEKEND</h2><p>${tr('这门两日课程可以与住宿和每日早餐组合。','This two-day course can be combined with accommodation and daily breakfast.')}</p><a href="#/stay" data-stay-course="Stitch Canoe">${tr('组合住宿','COMBINE WITH A STAY')} ↗</a></section>`:'';return html.replace('<section class="v3-course-status">',`${course?`<section class="final-course-summary"><div><small>TIME</small><strong>${course.meta}</strong></div><div><small>WHO CAN JOIN</small><strong>${course.aud}</strong></div><div><small>STATUS</small><strong>OPEN FOR ENROLLMENT</strong></div></section>`:''}${add}<section class="v3-course-status">`).replace('<input name="participants"','<select name="audience"><option>Adult</option><option>Parent + Child</option></select><label><span>'+tr('儿童年龄','Child Age')+'</span><input name="childAge" type="text"></label><label><span>'+tr('需要住宿？','Stay Needed?')+'</span><select name="stayNeeded"><option>No</option><option>Yes</option></select></label><input name="participants"')};

const finalProductBase=edProduct;
edProduct=function(id){let html=finalProductBase(id);if(!html||id==='dajiaoguai')return html;const choice=`<section class="final-buy-choice"><header><small>CHOOSE YOUR VERSION</small><h2>${tr('选择获得方式','Choose how to get it')}</h2></header><div><article><small>A / DIY</small><h3>${tr('自己组装','Assemble it yourself')}</h3><p><strong>SHIP HOME</strong><br>${tr('邮寄到家，自己完成打磨、组装和改色。','Ship home, then sand, assemble and recolor it yourself.')}</p><p><strong>MAKE AT PFS</strong><br>${tr('来到 PFS 完成打磨、组装和改色。','Come to PFS to sand, assemble and recolor it.')}</p></article><article><small>B / READY-TO-USE</small><h3>${tr('到手可用','Ready to use')}</h3><p><strong>DELIVERY</strong><br>${tr('由 PFS 完成后邮寄。','Completed by PFS and shipped.')}</p><p><strong>PICK UP AT PFS</strong><br>PICK UP · 95% OF STANDARD PRICE</p></article></div></section>`;html=html.replace('<section class="v3-product-status">',choice+'<section class="v3-product-status">');html=html.replace('<input name="city"',`<label><span>VERSION</span><select name="version" required><option value="">—</option><option>DIY</option><option>Ready-to-use</option></select></label><label><span>DELIVERY</span><select name="delivery" required><option value="">—</option><option>Ship</option><option>Pick Up at PFS</option></select></label><input name="city"`);return html};

function finalIdeaPage(){return `<article class="ed-page final-service">${edLead('BRING YOUR IDEA',{zh:'从想法到可以制作的东西。',en:'From idea to something you can make.'},{zh:'适合已有想法、草图、参考图、粗模型或仍需发展的设计。',en:'For an idea, sketch, reference image, rough model or design that still needs development.'})}<section class="final-service-pairs"><div><small>YOU MAY ALREADY HAVE</small><p>AN IDEA<br>A SKETCH<br>A REFERENCE IMAGE<br>A ROUGH MODEL<br>AN EXISTING DESIGN</p></div><div><small>PFS CAN WORK WITH</small><p>DESIGN DEVELOPMENT<br>PROTOTYPE<br>DIGITAL FABRICATION<br>MAKING<br>BUILDING</p></div></section>${p0Steps([[{zh:'想法',en:'Idea'},{zh:'说明对象、用途与问题。',en:'Describe the object, use and problem.'}],[{zh:'设计',en:'Design'},{zh:'确认适配性与设计范围。',en:'Confirm fit and design scope.'}],[{zh:'原型',en:'Prototype'},{zh:'在需要时验证方案。',en:'Test the proposal when needed.'}],[{zh:'制作',en:'Make'},{zh:'进入数字制造、制作或建造；并非每个项目需要全部阶段。',en:'Move into fabrication, making or building; not every project requires every stage.'}]])}<section class="v3-form-section">${p0IdeaForm()}</section></article>`}
function finalBuildPage(){return `<article class="ed-page final-service">${edLead('BUILD WITH PFS',{zh:'从真实场地到真实建造。',en:'From a real site to a real build.'},{zh:'适合家具、空间、建筑和装置等需要落地的真实项目。',en:'For furniture, space, building and installation projects that need to be realised.'})}<section class="p0-build-evidence"><a href="#/archive/songshan-2023">${filePic('archive-shanghai-interior.jpg',{zh:'松鼠与大山自然社区改造',en:'Songshan community adaptation'})}<div><small>2024 / SHANGHAI MINHANG</small><h2>SONGSHAN</h2><p>PLYWOOD / TIMBER COMPONENTS<br>CNC PREFABRICATION<br>DRY ASSEMBLY<br>DEMOUNTABLE CONSTRUCTION<br>NON-PROFESSIONAL PARTICIPATION</p><span>VIEW PROJECT ↗</span></div></a><a href="#/archive/big-foot">${filePic('asset-team-build-close.jpg',{zh:'大角怪公众共建',en:'Big Foot public co-build'})}<div><small>2024–2025 / PUBLIC CO-BUILD</small><h2>BIG FOOT</h2><p>${tr('公众参与真实建造。','Public participation in a real build.')}</p><span>VIEW PROJECT ↗</span></div></a></section>${p0Steps([[{zh:'任务说明',en:'Brief'},{zh:'项目、场地、目标、预算、时间与限制。',en:'Project, site, goal, budget, timing and constraints.'}],[{zh:'设计',en:'Design'},{zh:'设计、材料、结构与建造方式。',en:'Design, material, structure and build method.'}],[{zh:'原型 / 预制',en:'Prototype / Fabrication'},{zh:'原型、数字文件、CNC 与构件。',en:'Prototype, digital files, CNC and components.'}],[{zh:'建造',en:'Build'},{zh:'组装、施工或共建。',en:'Assembly, construction or co-build.'}],[{zh:'交付',en:'Handover'},{zh:'完成、使用与调整；项目可只使用部分阶段。',en:'Completion, use and adjustment; a project may use selected stages.'}]])}<section class="v3-form-section">${p0BuildForm()}</section></article>`}
function finalVenuePage(){return `<article class="ed-page final-service">${edLead('VENUE HIRE',{zh:'使用 PFS 场地。',en:'Use the PFS site.'},{zh:'用于团队活动、Retreat、工作坊或学校、品牌活动、拍摄和私人活动。',en:'For team activities, retreats, workshops or schools, brand events, shoots and private events.'})}<section class="p0-usecases"><span>TEAM ACTIVITY</span><span>RETREAT</span><span>WORKSHOP / SCHOOL</span><span>BRAND EVENT</span><span>SHOOTING</span><span>PRIVATE EVENT</span></section><section class="final-venue-scale"><div><small>SMALL</small><strong>UP TO 15</strong><span>FROM ¥3,000 / HALF DAY</span></div><div><small>MEDIUM</small><strong>UP TO 30</strong><span>FROM ¥6,000 / HALF DAY</span></div><div><small>LARGE / SITE USE</small><strong>30–80</strong><span>BY REQUEST</span></div><div><small>80+</small><strong>CUSTOM REQUEST</strong></div></section><p class="p0-cost-factors">SPACE / SETUP / EQUIPMENT / POWER / FOOD / PFS COURSE / ACTIVITY / PRODUCTION / LOAD-IN / LOAD-OUT / EXTENDED HOURS / CLEANING</p>${p0Steps([[{zh:'需求',en:'Request'},{zh:'提交活动需求。',en:'Submit the event needs.'}],[{zh:'讨论',en:'Discuss'},{zh:'确认空间和现场适配。',en:'Confirm site fit.'}],[{zh:'报价',en:'Quote'},{zh:'按实际范围报价。',en:'Quote the actual scope.'}],[{zh:'确认',en:'Confirm'},{zh:'确认日期与安排。',en:'Confirm date and setup.'}],[{zh:'付款 / 定金',en:'Payment / Deposit'},{zh:'按确认方案执行。',en:'Follow the agreed proposal.'}],[{zh:'活动',en:'Event'},{zh:'按现场指引使用场地。',en:'Use the site under guidance.'}]])}<section class="v3-form-section">${p0VenueForm()}</section></article>`}

edWork=function(){return `<article class="ed-page final-work">${edLead('05 / WORK WITH US',{zh:'与 PFS 共创',en:'WORK WITH US'},{zh:'按你现在拥有的内容，进入正确的合作路径。',en:'Choose a path based on what you already have.'})}<section class="final-work-paths"><a id="p-cut" href="#/p-cut"><small>01 / FILE READY</small><h2>P-CUT</h2><p>${tr('已有加工文件：数字文件 → CNC → 部件。','Fabrication file ready: digital file → CNC → parts.')}</p><span>GO TO P-CUT ↗</span></a><a id="bring-your-idea" href="#/bring-your-idea"><small>02 / NEEDS DESIGN</small><h2>BRING YOUR IDEA</h2><p>${tr('有想法、草图、参考图或设计，但仍需进一步发展。','An idea, sketch, reference image or design that still needs development.')}</p><span>IDEA → DESIGN → PROTOTYPE → MAKE ↗</span></a><a id="build-with-pfs" href="#/build-with-pfs" class="is-major"><small>03 / REAL PROJECT</small><h2>BUILD WITH PFS</h2><p>FURNITURE / SPACE / BUILDING / INSTALLATION</p><div>${filePic('archive-shanghai-interior.jpg',{zh:'Songshan 项目',en:'Songshan project'})}${filePic('asset-team-build-close.jpg',{zh:'Big Foot 项目',en:'Big Foot project'})}</div><strong>SONGSHAN · CNC PREFABRICATION / DRY ASSEMBLY / DEMOUNTABLE</strong><strong>BIG FOOT · PUBLIC CO-BUILD / REAL BUILDING</strong><span>BUILD WITH PFS ↗</span></a><a id="venue-hire" href="#/venue-hire"><small>04 / USE THE SITE</small><h2>VENUE HIRE</h2><p>TEAM ACTIVITY / RETREAT / WORKSHOP / SCHOOL / BRAND EVENT / SHOOTING / PRIVATE EVENT</p><span>VENUE HIRE ↗</span></a><section id="volunteer"><small>05 / PROJECT-BASED</small><h2>VOLUNTEER</h2><strong>${tr('当前没有开放的志愿者项目。','CURRENTLY NO OPEN VOLUNTEER PROJECTS')}</strong><p>${tr('新的参与机会随真实项目、日期、工作和安全要求发布。','New opportunities are published with a real project, date, work and safety requirements.')}</p></section></section></article>`};

const finalVisitBase=edVisit;
edVisit=function(){return finalVisitBase().replace(/<p>[^<]*(?:待确认|awaits confirmation)[^<]*<\/p>/gi,'').replace(tr('日常到访 / DAILY VISIT','DAILY VISIT'),tr('日常到访 / DAILY VISIT · 无需预约','DAILY VISIT · NO RESERVATION REQUIRED')).replace('</article>',`<section class="final-before-visit"><h2>${tr('来之前','BEFORE YOU COME')}</h2>${p0Facts([['OPEN','10:00–18:00'],['COURSES',tr('通过 BUILDING 报名','JOIN THROUGH BUILDING')],['STAY',tr('提前申请','REQUEST IN ADVANCE')],['EVENTS',tr('查看 WHAT’S ON','SEE WHAT’S ON')],['DIRECTIONS','AMAP / 121.075687, 31.671134'],['CONTACT','info@pfs.cool']])}</section></article>`)};

edAbout=function(){return `<article class="ed-page final-about">${edLead('ABOUT / PARTY FRIEND SHIP',{zh:'PFS 建造学校',en:'PFS Building School'},{zh:'分享更可持续的生活办法，共享知识，共享制造。',en:'Sharing sustainable living practices, knowledge, and collaborative manufacturing.'})}<section><p>${tr('PFS 的目标是生产足够多的可改造家居套件和课程，覆盖差异化的住宅建筑和与家相关的物品需求，在让生活变特别的同时不对地球添加新的负担。','PFS aims to produce enough adaptable home kits and courses to meet varied residential and household needs, making life distinct without adding new burdens to the planet.')}</p></section><section class="final-name"><div><small>PARTY / 派对</small><strong>${tr('乐趣','Fun')}</strong></div><div><small>FRIEND / 朋友</small><strong>${tr('人、社交、网络','People, social connection, network')}</strong></div><div><small>SHIP / 飞船</small><strong>${tr('冒险、改变','Adventure, change')}</strong></div></section>${p0Link('archive',{zh:'SEE WHAT WE’VE BUILT / PROJECT ARCHIVE',en:'SEE WHAT WE’VE BUILT / PROJECT ARCHIVE'})}</article>`};

edFaq=function(){const q=[[{zh:'可以不参加课程直接来 PFS 吗？',en:'Can I visit without joining a course?'},{zh:'可以。PFS 每天 10:00–18:00 开放普通到访。课程、住宿及特定活动通过对应页面报名或申请。',en:'Yes. PFS is open daily 10:00–18:00 for regular visits. Apply for courses, stays and specific events through their pages.'}],[{zh:'PFS 已经全部建完了吗？',en:'Is PFS fully built?'},{zh:'PFS 仍在持续建造和使用中。部分工作、机器及施工区域按照现场开放状态进入。',en:'PFS remains in use and under construction. Work, machine and construction areas open according to site conditions.'}],[{zh:'可以带孩子来吗？',en:'Can I bring children?'},{zh:'PFS 有 Parent + Child 建造课程。普通到访儿童需由成人陪同。',en:'PFS has Parent + Child building courses. Children on regular visits must be accompanied by an adult.'}],[{zh:'住宿一定要参加课程吗？',en:'Must I join a course when staying?'},{zh:'不需要。可以单独申请住宿，也可以与当前开放的建造课程组合。',en:'No. Request a stay alone or combine it with a current building course.'}],[{zh:'住宿包含早餐吗？',en:'Does a stay include breakfast?'},{zh:'包含。早餐时间为 08:00–10:00。',en:'Yes. Breakfast is served 08:00–10:00.'}],[{zh:'可以住很多天吗？',en:'Can I stay for many days?'},{zh:'可以提交 7 晚以上的长期住宿需求。',en:'You can request a long stay of 7 nights or more.'}],[{zh:'两天课程可以和住宿一起吗？',en:'Can a two-day course include a stay?'},{zh:'可以。适合连续两天完成的课程可以组合为 Build Weekend。',en:'Yes. A course completed over two consecutive days can become a Build Weekend.'}],[{zh:'商品可以买成品吗？',en:'Can I buy a finished product?'},{zh:'可以。当前商品提供 DIY 和到手可用两种形式。',en:'Yes. Current products offer DIY and ready-to-use versions.'}],[{zh:'我想自己组装怎么办？',en:'What if I want to assemble it myself?'},{zh:'选择 DIY。可以邮寄到家完成，也可以在 PFS 完成打磨、组装和改色。',en:'Choose DIY. Finish at home after shipping, or sand, assemble and recolor it at PFS.'}],[{zh:'我已经有 CNC 加工文件怎么办？',en:'What if I already have a CNC file?'},{zh:'使用 P-CUT。',en:'Use P-CUT.'}],[{zh:'我只有想法怎么办？',en:'What if I only have an idea?'},{zh:'使用 Bring Your Idea。',en:'Use Bring Your Idea.'}],[{zh:'我有真实场地或建筑项目怎么办？',en:'What if I have a real site or building project?'},{zh:'使用 Build With PFS。',en:'Use Build With PFS.'}],[{zh:'可以租用 PFS 办活动吗？',en:'Can I hire PFS for an event?'},{zh:'可以提交 Venue Hire 需求。',en:'Yes. Submit a Venue Hire request.'}]];return `<article class="ed-page final-faq">${edLead('INFORMATION / FAQ',{zh:'行动问题',en:'Practical questions'},{zh:'到访、住宿、购买、加工与合作。',en:'Visit, stay, purchase, fabrication and collaboration.'})}<div>${q.map((x,i)=>`<details ${i===0?'open':''}><summary><small>${String(i+1).padStart(2,'0')}</small><strong>${ed(x[0])}</strong></summary><p>${ed(x[1])}</p></details>`).join('')}</div></article>`};
