/* V3 recovery layer: confirmed operating facts and honest inquiry handoff. */
const v3Field=(name,label,type='text',required=true,extra='')=>`<label><span>${ed(label)}</span><input name="${name}" type="${type}" ${required?'required':''} ${extra}></label>`;
const v3Form=(type,id,fields,title,copy,button)=>`<form class="v3-inquiry" data-inquiry="${type}" data-object="${id}"><header><span class="ed-kicker">${type} / INQUIRY</span><h3>${ed(title)}</h3><p>${ed(copy)}</p></header><div class="v3-form-grid">${fields.join('')}</div><label class="v3-wide"><span>${tr('补充说明','Notes')}</span><textarea name="notes" rows="4"></textarea></label><button type="submit">${ed(button)} ↗</button><small>${tr('这会打开邮件应用并生成结构化内容；只有在你确认发送后才会送达 PFS。','This opens your email app with structured details. Nothing is delivered until you send it.')}</small></form>`;
const v3ContactFields=()=>[v3Field('name',{zh:'姓名',en:'Name'}),v3Field('contact',{zh:'电话 / 微信',en:'Phone / WeChat'}),v3Field('email',{zh:'邮箱',en:'Email'},'email')];
const v3Append=(html,content)=>{const at=html.lastIndexOf('</article>');return at<0?html+content:html.slice(0,at)+content+html.slice(at)};

const v3HeaderBase=renderHeader;
renderHeader=function(){v3HeaderBase();const end=$('#footer .foot-end');if(end)end.insertAdjacentHTML('beforebegin',`<div class="v3-footer-facts"><div><small>VISIT</small><strong>OPEN DAILY / 10:00–18:00</strong><span>${tr('中国江苏省太仓市璜泾镇孟河村伍鹿路和花木路交叉口','Intersection of Wulu Road & Huamu Road, Menghe Village, Huangjing Town, Taicang, Jiangsu, China')}</span></div><div><small>CONTACT</small><a href="mailto:info@pfs.cool">info@pfs.cool</a><span>WECHAT / XIAOHONGSHU · pfspfs000</span><span>OFFICIAL ACCOUNT · PFS4YOU</span></div></div>`)};

const v3VisitBase=edVisit;
edVisit=function(){let html=v3VisitBase();const facts=`<section class="v3-visit-facts"><div><small>OPEN DAILY</small><strong>10:00–18:00</strong></div><div><small>ADDRESS</small><strong>${tr('中国江苏省太仓市璜泾镇孟河村伍鹿路和花木路交叉口','Intersection of Wulu Road & Huamu Road, Menghe Village, Huangjing Town, Taicang, Jiangsu, China')}</strong><span>121.075687, 31.671134</span></div><a href="https://uri.amap.com/marker?position=121.075687,31.671134&name=%E6%B4%BE%E5%AF%B9%E6%9C%8B%E5%8F%8B%E7%9A%84%E9%A3%9E%E8%88%B9&coordinate=gaode&callnative=1" target="_blank" rel="noreferrer" data-analytics="visit_directions_click">${tr('导航到 PFS','Open directions')} ↗</a></section>`;return html.replace('<div class="cf-visit-hero">',facts+'<div class="cf-visit-hero">').replace(tr('日常到访','Daily visit'),tr('日常到访 / DAILY VISIT','DAILY VISIT')).replace(tr('近期活动','Dated activities'),tr('参加课程或活动 / BUILDING','BUILDING / COURSES'))};

const v3StayBase=edStay;
edStay=function(){let html=v3StayBase();const essential=`<section class="v3-essential"><div><small>CHECK-IN</small><strong>FROM 14:00</strong></div><div><small>CHECK-OUT</small><strong>BY 12:00</strong></div><div><small>BREAKFAST</small><strong>08:00–10:00</strong><span>INCLUDED</span></div></section>`;const fields=[v3Field('arrival',{zh:'到达日期',en:'Arrival Date'},'date'),v3Field('departure',{zh:'离开日期',en:'Departure Date'},'date'),v3Field('guests',{zh:'人数',en:'Guests'},'number',true,'min="1"'),`<label><span>${tr('房型','Accommodation Type')}</span><select name="accommodation" required><option value="">—</option><option>SINGLE</option><option>DOUBLE</option><option>SHARED</option></select></label>`,v3Field('arrivalTime',{zh:'预计到达时间',en:'Estimated Arrival Time'},'time',false),v3Field('course',{zh:'希望参加的课程',en:'Course Interest'},'text',false),v3Field('children',{zh:'儿童人数 / 年龄',en:'Children / Ages'},'text',false),v3Field('dietary',{zh:'饮食需求',en:'Dietary Requirements'},'text',false),...v3ContactFields(),v3Field('emergency',{zh:'紧急联系人（需要时）',en:'Emergency Contact (if relevant)'},'text',false)];const form=v3Form('STAY','stay',fields,{zh:'住宿申请',en:'Stay Request'},{zh:'PFS 会在收到邮件后确认住宿、课程需求与相关费用。',en:'PFS will confirm accommodation, course needs and related fees after receiving your email.'},{zh:'准备住宿申请邮件',en:'Prepare Stay Request Email'});return html.replace('<div class="field-hero',essential+'<div class="field-hero').replace('<section class="cf-breakfast">','<section class="cf-breakfast"><div class="v3-breakfast-fact"><strong>08:00–10:00</strong><span>INCLUDED WITH YOUR STAY</span></div>').replace('<section class="cf-stay-action">',`<section class="v3-stay-rule"><strong>${tr('住宿并不自动获得工作区、机器或施工区域的使用权限。','A stay does not automatically include access to workspaces, machines or construction zones.')}</strong></section><section id="stay-request" class="v3-form-section">${form}</section><section class="cf-stay-action">`)};

const v3BuildingBase=edBuilding;
edBuilding=function(){let html=v3BuildingBase().replaceAll('<small>COURSE /','<small>'+tr('开放报名 / COURSE /','OPEN FOR ENROLLMENT / COURSE /'));return html.replace('<section class="real-builds"',`<section class="v3-building-evidence"><div>${filePic('asset-building-process.png',{zh:'制作与建造过程',en:'Making and building process'})}<p>${tr('材料、工具与双手在真实过程中相遇。','Materials, tools and hands meet in a real process.')}</p></div><div>${filePic('asset-team-work.png',{zh:'设计与制作过程',en:'Design and making process'})}<p>${tr('协作贯穿设计、数字制造与现场制作。','Collaboration runs through design, digital fabrication and making.')}</p></div></section><section class="real-builds"`)};

const v3CourseBase=edCourse;
edCourse=function(id){const html=v3CourseBase(id);if(!html)return null;const fields=[...v3ContactFields(),v3Field('preferredDate',{zh:'希望日期',en:'Preferred Date'},'date',false),v3Field('participants',{zh:'参与人数',en:'Participants'},'number',false,'min="1"')];const form=v3Form('COURSE',id,fields,{zh:'开放报名',en:'Open for Enrollment'},{zh:'没有公开日期也可以提出报名或日期需求；这不会创建虚构活动。',en:'You can enquire or request a date when no public event date exists.'},{zh:'准备课程询问邮件',en:'Prepare Course Inquiry Email'});return html.replace('</article>',`<section class="v3-course-status"><strong>OPEN FOR ENROLLMENT</strong><span>${tr('ENQUIRE TO JOIN / REQUEST A DATE','ENQUIRE TO JOIN / REQUEST A DATE')}</span></section><section class="v3-course-safety"><h2>${tr('参加制作课程','For hands-on sessions')}</h2><p>${tr('穿包头鞋和适合工作的衣物；长发扎起，避免宽松饰品。工具使用前接受现场说明，部分机器仅可在工作人员监督下操作。','Wear closed-toe shoes and work clothing; tie back long hair and avoid loose accessories. Tool briefing comes first, and some machines are staff-supervised only.')}</p></section><section class="v3-form-section">${form}</section></article>`)};

const v3ShopBase=edShop;
edShop=function(){const entry=`<section class="v3-shop-pcut" data-shop-group="pcut"><div><span class="ed-kicker">SERVICE / P-CUT</span><h2>${tr('已有数字文件？从 SHOP 进入加工。','Have a digital file? Start fabrication from SHOP.')}</h2><p>${tr('P-CUT 是独立数字制造服务；SHOP 与 WORK WITH US 进入同一 canonical 页面。','P-CUT is a standalone digital fabrication service. SHOP and WORK WITH US open the same canonical page.')}</p>${cfPath('p-cut',{zh:'进入 P-CUT / 获取报价',en:'Open P-CUT / Get a Quote'})}</div>${filePic('asset-cnc-router.jpg',{zh:'P-CUT CNC Router',en:'P-CUT CNC Router'})}</section>`;return v3ShopBase().replace('<nav class="ed-shop-filters"',entry+'<nav class="ed-shop-filters"').replaceAll('/ PFS OBJECT</small>',' / AVAILABLE TO BUY</small>')};

const v3ProductBase=edProduct;
edProduct=function(id){const html=v3ProductBase(id);if(!html)return null;const node=id==='dajiaoguai'?{zh:'大角怪数字盖房套件',en:'Dajiaoguai Building Kit'}:productNode(id);const fields=[v3Field('product',{zh:'产品',en:'Product'},'text',true,`value="${esc(zh?node.zh:node.en)}" readonly`),v3Field('quantity',{zh:'数量',en:'Quantity'},'number',true,'min="1"'),v3Field('city',{zh:'配送城市',en:'Delivery City'}),...v3ContactFields()];const form=v3Form('PRODUCT',id,fields,{zh:'购买询问',en:'Purchase Request'},{zh:'PFS 会确认产品、数量、生产 / 库存情况与配送。可购买不等于即时库存。',en:'PFS will confirm product, quantity, production or stock situation and delivery. Available to buy does not mean immediate stock.'},{zh:'BUY THIS / 准备购买邮件',en:'BUY THIS / Prepare Purchase Email'});return html.replace('</article>',`<section class="v3-product-status"><strong>${id==='dajiaoguai'?'GET A QUOTE':'AVAILABLE TO BUY'}</strong><span>${tr('价格与库存 / 生产情况在询问后确认。','Price and stock or production status are confirmed after inquiry.')}</span></section><section class="v3-form-section">${form}</section></article>`)};

edPCut=function(){const fields=[v3Field('use',{zh:'用途',en:'Intended Use'}),v3Field('material',{zh:'材料需求',en:'Material Need'},'text',false),v3Field('quantity',{zh:'数量',en:'Quantity'},'number',false,'min="1"'),v3Field('dimensions',{zh:'大致尺寸',en:'Approximate Dimensions'},'text',false),...v3ContactFields()];const form=v3Form('P-CUT','p-cut',fields,{zh:'提交项目详情',en:'Submit Project Details'},{zh:'此表不上传文件。邮件发出后，PFS 会跟进文件检查、加工方式和报价。',en:'This form does not upload a file. After you send the email, PFS can follow up on file review, fabrication and quotation.'},{zh:'SUBMIT PROJECT DETAILS',en:'SUBMIT PROJECT DETAILS'});return `<article class="ed-page ed-pcut v3-pcut">${edLead('P-CUT / DIGITAL FABRICATION',{zh:'从文件到真实零件。',en:'From file to real part.'},{zh:'已有可加工数字文件时进入 P-CUT；仍需设计或打样时进入 Bring Your Idea。',en:'Choose P-CUT for a manufacturable digital file; choose Bring Your Idea when design or prototyping is still needed.'})}<section class="v3-pcut-hero">${filePic('asset-cnc-router.jpg',{zh:'P-CUT CNC Router',en:'P-CUT CNC Router'},'ed-wide')}<div><h2>${tr('数字文件 → 材料 → 零件','Digital file → material → part')}</h2><p>${tr('准备文件、用途、数量与大致尺寸。机器型号、工作范围、格式与公差在沟通中确认。','Prepare the file, intended use, quantity and approximate dimensions. Machine model, working area, formats and tolerances are confirmed through discussion.')}</p><a href="#pcut-inquiry">GET A QUOTE ↓</a></div></section><section class="v3-pcut-flow"><span>01 FILE</span><span>02 CHECK</span><span>03 QUOTE</span><span>04 CUT</span><span>05 PICK UP / SHIP</span><span>06 BUILD</span><p>${tr('实际加工条件在报价前确认。','Actual fabrication conditions are confirmed before quotation.')}</p></section><section class="v3-pcut-split"><div><h2>P-CUT</h2><p>${tr('已有可加工文件，需要加工零件。','You have a manufacturable file and need parts fabricated.')}</p></div><a href="#/work-with-us?section=idea"><h2>BRING YOUR IDEA</h2><p>${tr('只有想法或草图，需要继续设计与打样。','You have an idea or sketch that needs design and prototyping.')}</p></a></section><section id="pcut-inquiry" class="v3-form-section">${form}</section></article>`};

const v3WorkBase=edWork;
edWork=function(){const venue=v3Form('VENUE','venue-hire',[v3Field('use',{zh:'活动类型',en:'Use Type'}),v3Field('date',{zh:'希望日期',en:'Preferred Date'},'date',false),v3Field('guests',{zh:'预计人数',en:'Estimated Guests'},'number',false,'min="1"'),...v3ContactFields()],{zh:'场地询问',en:'Venue Request'},{zh:'适用于团队活动、Retreat、品牌活动、拍摄、学校与私人活动。',en:'For team activities, retreats, brand events, shoots, schools and private events.'},{zh:'准备场地询问邮件',en:'Prepare Venue Request Email'});const project=v3Form('PROJECT','build-with-pfs',[v3Field('project',{zh:'项目 / 场地',en:'Project / Site'}),v3Field('location',{zh:'地点',en:'Location'},'text',false),v3Field('stage',{zh:'当前阶段',en:'Current Stage'},'text',false),...v3ContactFields()],{zh:'开始一个项目或建造',en:'Start a Project or Build'},{zh:'家具、空间、产品想法或真实场地任务都可成为合作起点。',en:'A furniture, space or product idea, or a real site task, can begin a collaboration.'},{zh:'准备项目询问邮件',en:'Prepare Project Inquiry Email'});return v3Append(v3WorkBase(),`<section class="v3-work-forms"><details><summary>VENUE REQUEST</summary>${venue}</details><details><summary>BRING YOUR IDEA / BUILD WITH PFS</summary>${project}</details></section>`) };

const v3SecondaryBase=edSecondary;
edSecondary=function(id){if(id!=='contact')return v3SecondaryBase(id);return `<article class="ed-page v3-contact">${edLead('CONTACT',{zh:'联系 PFS',en:'Contact PFS'},{zh:'到访、住宿、课程、购买与合作都从已确认渠道开始。',en:'Visits, stays, courses, purchases and collaborations begin with confirmed contact channels.'})}<section class="v3-contact-grid"><div><small>GENERAL</small><a href="mailto:info@pfs.cool">info@pfs.cool</a></div><div><small>SECONDARY EMAIL</small><a href="mailto:partyfriendship@126.com">partyfriendship@126.com</a></div><div><small>WECHAT</small><strong>pfspfs000</strong></div><div><small>WECHAT OFFICIAL ACCOUNT</small><strong>PFS4YOU</strong></div><div><small>XIAOHONGSHU</small><strong>pfspfs000</strong></div></section><section class="v3-contact-visit"><strong>OPEN DAILY / 10:00–18:00</strong><p>${tr('中国江苏省太仓市璜泾镇孟河村伍鹿路和花木路交叉口','Intersection of Wulu Road & Huamu Road, Menghe Village, Huangjing Town, Taicang, Jiangsu, China')}</p><a href="https://uri.amap.com/marker?position=121.075687,31.671134&name=%E6%B4%BE%E5%AF%B9%E6%9C%8B%E5%8F%8B%E7%9A%84%E9%A3%9E%E8%88%B9&coordinate=gaode&callnative=1" target="_blank" rel="noreferrer">AMAP / ${tr('导航到 PFS','Directions')} ↗</a></section></article>`};

function setupV3Forms(){document.querySelectorAll('[data-inquiry]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const lines=[`Inquiry Type: ${form.dataset.inquiry}`,`Related Object: ${form.dataset.object}`,...[...new FormData(form)].filter(([,v])=>String(v).trim()).map(([k,v])=>`${k}: ${v}`)];location.href=`mailto:info@pfs.cool?subject=${encodeURIComponent(`PFS ${form.dataset.inquiry} — ${form.dataset.object}`)}&body=${encodeURIComponent(lines.join('\n'))}`}))}
