const zh = new URLSearchParams(location.search).get('lang') !== 'en';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const tr = (a,b) => zh ? a : b;
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name = n => esc(zh ? n.zh : n.en);
const pair = n => `<span class="title-primary">${name(n)}</span><span class="title-secondary">${esc(zh?n.en:n.zh)}</span>`;
const a = (path,content,cls='') => `<a class="${cls}" href="#/${typeof canonicalPath==='function'?canonicalPath(path):path}">${content}</a>`;
const note = (cn,en) => `<p class="notice">${esc(tr(cn,en))}</p>`;
let data, canonicalData, slide=0, mode='list', selected=0, picked='', month=new Date(new Date().getFullYear(),new Date().getMonth(),1);
const routes = new Map();
function register(nodes,parent='') { nodes.forEach(n=>{n.path=n.route||[parent,n.id].filter(Boolean).join('/');routes.set(n.path,n);register(n.children||[],n.path)}) }
const heroFiles=[1,2,3,4,5];
const productImages={avant:'object-avant.jpg',coaster:'object-coaster.jpg',clock:'object-clock.jpg',animals:'object-animals.jpg',badger:'object-badger.jpg',opener:'object-opener.jpg',stool:'object-stool.jpg',cat:'object-cat.jpg',cabinet:'cabinet.jpg'};
const productNames=['avant','coaster','clock','animals','badger','opener','stool','cat','cabinet','swish','neubau'];
function image(file,alt,cls=''){return `<img class="${cls}" src="assets/${file}" alt="${esc(alt)}" loading="${file.startsWith('hero-')?'eager':'lazy'}">`}
function header(){renderHeader()}
function hero(){return `<section class="hero" aria-label="${tr('PFS 建造图像','PFS building photographs')}"><div class="hero-frame" tabindex="0"><div class="hero-track">${heroFiles.map((x,i)=>`<figure>${image('hero-'+x+'.jpg',tr(['山地环境施工与建造','山地与场地远景','人员安装结构','夜间施工','木材加工与群体制作'][i],['Building in the mountain landscape','Mountain site and architecture','Installing a structure','Building at night','Timber processing and collective making'][i]))}</figure>`).join('')}</div><div class="slider-controls"><button data-slide="-1" aria-label="${tr('上一张','Previous slide')}">←</button><button data-slide="1" aria-label="${tr('下一张','Next slide')}">→</button></div></div><div class="hero-bottom"><div class="hero-copy"><h1>#可持续生活 更多灵感</h1><p>Sustainability Made Fun!#</p></div><div class="dots">${heroFiles.map((_,i)=>`<button data-goto="${i}" aria-label="${tr('第','Slide ')}${i+1}${zh?'张':''}">0${i+1}</button>`).join('')}</div></div></section>`}
function show(i){slide=(i+5)%5;$('.hero-track').style.transform=`translateX(-${slide*100}%)`;$$('[data-goto]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.goto)===slide);b.setAttribute('aria-pressed',Number(b.dataset.goto)===slide)})}
function whats(){return `<section class="section" id="whats-on"><div class="section-head"><span class="eyebrow">01 / PROGRAMME</span><h2>WHAT'S ON</h2><p>${tr('在列表或日历中查看 PFS 正在发生的内容。','Explore what is happening at PFS as a list or calendar.')}</p></div><div class="switch" role="group" aria-label="${tr('显示方式','Display mode')}"><button data-view="list">${tr('列表','List')}</button><button data-view="calendar">${tr('日历','Calendar')}</button></div><div id="listing-content" aria-live="polite"></div></section>`}
function listing(){return editorialListing()}
function map(){return illustratedMap()}
function choose(i){mapPanel(i,true)}
function home(){return hero()+whats()+map()}
function sectionList(nodes,depth=0){return `<div class="editorial-list depth-${depth}">${nodes.map((n,i)=>`<article class="editorial-row"><span class="row-no">${String(i+1).padStart(2,'0')}</span><div><h3>${a(n.path,pair(n))}</h3>${summary(n)}${n.children?.length&&depth<2?sectionList(n.children,depth+1):''}</div><span class="row-arrow">↗</span></article>`).join('')}</div>`}
function summary(n){const d=data.detailByPath?.[n.path]||(n.path.startsWith('shop/kits/')?null:data.detail[n.id]);return d?`<p>${esc(tr(...d))}</p>`:''}
function crumb(path){const bits=path.split('/');return `<div class="breadcrumbs">${a('',tr('首页','Home'))}${bits.map((_,i)=>{const p=bits.slice(0,i+1).join('/'),n=routes.get(p);return ` <span>/</span> ${n?a(p,name(n)):esc(bits[i])}`}).join('')}</div>`}
function page(n){const root=n.path.split('/')[0],story=data.stories[root],isRoot=n.path===root;return `<article class="page">${crumb(n.path)}<div class="page-heading"><span class="eyebrow">PFS / ${esc(root.toUpperCase())}</span><h1>${pair(n)}</h1>${isRoot&&story?`<p class="page-lead">${esc(tr(...story.lead))}</p>`:summary(n)}</div>${isRoot&&story?`<div class="story-sections">${story.sections.map(([heading,copy])=>`<section><h2>${esc(heading.split(' / ')[zh?0:1])}</h2><p>${esc(copy.split(' / ')[zh?0:1])}</p></section>`).join('')}</div>`:''}${n.children?.length?sectionList(n.children):''}${!n.children?.length?detailExtra(n):''}${!n.children?.length?related(n):''}</article>`}
function related(n){const parent=n.path.split('/').slice(0,-1).join('/');const group=routes.get(parent);const siblings=(group?.children||[]).filter(x=>x.path!==n.path);return siblings.length?`<nav class="related" aria-label="${tr('同一主题','Related pages')}"><h2>${tr('继续探索','Continue exploring')}</h2>${siblings.map(x=>a(x.path,name(x)+' ↗')).join('')}</nav>`:''}
function detailExtra(n){const facts=data.detailSections?.[n.path];const sections=facts?`<div class="story-sections detail-sections">${zh?facts.map(([head,copy])=>`<section><h2>${esc(head)}</h2><p>${esc(copy)}</p></section>`).join(''):`<section><h2>Source context</h2><p>${esc(data.detail[n.id]?.[1]||'This subject is recorded in PFS source materials.')}</p></section><section><h2>Current details</h2><p>Availability, timing and participation details await confirmation.</p></section>`}</div>`:'';const p=n.path;if(p.startsWith('building/courses'))return sections+courseDetail(n);if(p==='shop/online/building-kits/dajiaoguai')return sections+buildingKitDetail();if(p.startsWith('shop/kits'))return sections+productDetail(n);if(p==='visit/guidebook')return sections+`<div class="page-map-link">${a('map',tr('查看九节点空间关系示意 ↗','Explore the nine-node map ↗'),'text-link')}</div>`;if(p==='shop/online')return sections+`<div class="page-map-link">${a('shop/kits',tr('浏览 11 件产品资料 ↗','Browse 11 product records ↗'),'text-link')}</div>`;if(p==='building/join')return sections+`<div class="page-map-link">${a('whats-on',tr('查看 WHAT’S ON ↗','See WHAT’S ON ↗'),'text-link')}</div>`;if(p==='about')return sections+`<blockquote>分享更可持续的生活办法，共享知识，共享制造。<span>Sharing sustainable living practices, knowledge, and collaborative manufacturing.</span></blockquote>`;if(p==='faq')return sections+`<div class="story-sections">${data.pages.map(x=>`<section><h2>${name(x)}</h2><p>${tr('具体信息待确认。','Details await confirmation.')}</p></section>`).join('')}</div>`;return sections}
function courseDetail(n){if(n.children?.length)return '';const group=n.path.split('/').slice(0,-1).join('/');const noteText=tr('课程资料为历史来源事实；当前开课、课时、导师、价格和报名方式待确认。','Course records are historical source facts; current schedules, duration, instructors, prices and registration await confirmation.');return `<div class="detail-context"><span class="eyebrow">COURSE LIBRARY / SOURCE FACT</span><p>${noteText}</p>${a(group,tr('返回课程分类 ←','Back to course group ←'),'text-link')}</div>`}
function buildingKitDetail(){const kit=data.buildingKit;return `<div class="building-kit-detail">${image('building-kit-source.jpg',tr('PFS 大角怪数字盖房套件原始视觉资料','Original PFS Dajiaoguai building kit source image'))}<div><span class="eyebrow">PFS SOURCE FACT / BUILDING KITS</span><h2>${tr('大角怪 · 数字盖房套件','Dajiaoguai · Open Source Building Kit')}</h2><p>${esc(tr(kit.original[0],kit.title.en))}</p><p>${esc(tr(kit.original[1],kit.original[1]))}</p><h3>${tr('历史资料记录的套件内容','Components recorded in source')}</h3><ul>${kit.components.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${note('以上为历史产品资料，当前技术规格、售价、库存、交付及购买方式待确认。','This is a historical product record. Current specifications, price, stock, delivery and purchase method await confirmation.')}</div></div>`}
function productDetail(n){if(n.children?.length)return '';const imageFile=productImages[n.id];return `<div class="product-detail66">${imageFile?image(imageFile,tr(`${n.zh}产品资料图片`,`Source image for ${n.en}`),'product-original66'):`<div class="asset-note">${tr('当前无经确认的产品图片','No confirmed product image')}</div>`}<div><span class="eyebrow">PFS / PRODUCT RECORD</span><p>${esc(tr(...data.detail[n.id]))}</p>${n.id==='cabinet'?`<p>${tr('富柜系列以新西兰松木多层板（LVL / Laminated Veneer Lumber）及数字榫卯为资料中记录的材料与结构。','The source describes Fugui Cabinet using New Zealand pine LVL / Laminated Veneer Lumber and digital joinery.')}</p>`:''}${note('产品资料不代表当前在售。价格、库存、规格和购买入口待确认。','This record does not confirm current sale status. Price, stock, specifications and purchase channel await confirmation.')}${a('shop/kits',tr('返回产品索引 ←','Back to product index ←'),'text-link')}</div></div>`}
function space(id){const n=data.spaces.find(x=>x.id===id);if(!n)return null;return `<article class="page">${crumb('spaces/'+id)}<div class="page-heading"><span class="eyebrow">PFS / SPACE ${String(data.spaces.indexOf(n)+1).padStart(2,'0')}</span><h1>${pair(n)}</h1><p class="page-lead">${esc(zh?n.description.zh:n.description.en)}</p></div><div class="detail-context">${note('地图为空间关系示意 / 非实测平面；当前开放状态待确认。','The map is a spatial relationship diagram, not a surveyed plan. Current access awaits confirmation.')}${a('map',tr('返回地图 ←','Back to map ←'),'text-link')}</div></article>`}
let heroTimer;function setupHero(){clearInterval(heroTimer);if(!$('.hero-track'))return;show(slide);$$('[data-slide]').forEach(b=>b.onclick=()=>show(slide+Number(b.dataset.slide)));$$('[data-goto]').forEach(b=>b.onclick=()=>show(Number(b.dataset.goto)));const frame=$('.hero-frame');frame.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();show(slide+(e.key==='ArrowRight'?1:-1))}};let sx=0;frame.ontouchstart=e=>sx=e.changedTouches[0].screenX;frame.ontouchend=e=>{const dx=e.changedTouches[0].screenX-sx;if(Math.abs(dx)>45)show(slide+(dx<0?1:-1))};if(!matchMedia('(prefers-reduced-motion: reduce)').matches)heroTimer=setInterval(()=>{if(!frame.matches(':hover,:focus-within')&&!document.hidden)show(slide+1)},6500)}
function render(){header();const raw=location.hash.replace(/^#\/?/,'').replace(/\/$/,'');const [path,params]=raw.split('?');const canonical=canonicalPath(path);if(canonical!==path){location.replace('#/'+canonical);return}let html=!path?home():path==='map'?map():path==='whats-on'?whats():path==='search'?edSearch():path==='p-cut'?edPCut():path==='bring-your-idea'?finalIdeaPage():path==='build-with-pfs'?finalBuildPage():path==='venue-hire'?finalVenuePage():path.startsWith('events/')?edEvent(path.split('/')[1]):path.startsWith('archive/')?edProject(path.split('/')[1]):path==='archive'?edArchive():path.startsWith('courses/')?edCourse(path.split('/')[1]):path.startsWith('products/')?edProduct(path.split('/')[1]):path.startsWith('spaces/')?(path.endsWith('shipyard')||path.endsWith('school')?edSpace(path.split('/')[1]):null):({visit:edVisit,stay:edStay,building:edBuilding,shop:edShop,work:edWork,'work-with-us':edWork,about:edAbout,faq:edFaq,contact:()=>edSecondary('contact')}[path]?.()||null);if(!html&&routes.has(path))html=page(routes.get(path));$('#main').innerHTML=html||`<article class="page v3-not-found"><h1>${tr('这里没有这条记录。','This record is not here.')}</h1><nav>${a('visit','VISIT')}${a('building','BUILDING')}${a('shop','SHOP')}${a('archive','PROJECT ARCHIVE')}</nav></article>`;listing();setupNavigation();setupMap();setupHero();setupSearch();setupShopFilters(params);setupV3Forms();setupP0();setupV20();document.title=(path?`${esc(path.replaceAll('/',' / '))} — `:'')+'Party Friend Ship｜派对朋友的飞船';document.documentElement.lang=zh?'zh-CN':'en';const section=new URLSearchParams(params||'').get('section');if(section&&document.getElementById(section))requestAnimationFrame(()=>document.getElementById(section).scrollIntoView({behavior:'instant'}));else scrollTo({top:0,behavior:'instant'})}
Promise.all([fetch('content-v66.json').then(r=>{if(!r.ok)throw Error('content');return r.json()}),fetch('editorial-content.json').then(r=>{if(!r.ok)throw Error('editorial');return r.json()}),fetch('canonical-content.json').then(r=>{if(!r.ok)throw Error('canonical');return r.json()})]).then(([d,e,c])=>{data=d;editorialData=e;canonicalData=c;register(d.pages);register(d.footer);addCourseDescriptions();addProductDescriptions();window.addEventListener('hashchange',render);render()}).catch(e=>{$('#main').innerHTML=`<article class="page"><p>${tr('内容加载失败','Content could not load')}</p></article>`;console.error(e)});
function addCourseDescriptions(){const descriptions={openbike:['设计、CNC、激光与 3D 打印；历史资料记录成人与亲子参与。','Design, CNC, laser and 3D printing; source records adult and family participation.'],'stripe-canoe':['设计、开料、榫卯拼接、蒸汽弯曲、树脂封胶、打磨与光油。','Design, cutting, joinery, steam bending, resin sealing, sanding and varnish.'],'stitch-canoe':['设计、开料、缝接、树脂封胶、打磨与光油。','Design, cutting, stitching, resin sealing, sanding and varnish.'],paddle:['设计、开料、塑形、打磨与防水。','Design, cutting, shaping, sanding and waterproofing.'],furniture:['家具课程与国际家具艺术家合作课程见于历史资料。','Furniture courses and collaborations with international furniture artists appear in source materials.'],'digital-furniture':['资料记录 20 种不同数字家具；具体课程安排待确认。','Source materials record 20 digital furniture designs; current courses await confirmation.'],'rocket-stool':['火箭凳课程属于大角怪小屋公司课程资料。','Rocket Stool appears in the Dajiaoguai Cabin Company course records.'],swish:['Swish 课程属于大角怪小屋公司课程资料。','Swish appears in the Dajiaoguai Cabin Company course records.'],neubau:['Neubau 组合架课程属于大角怪小屋公司课程资料。','Neubau shelving appears in the Dajiaoguai Cabin Company course records.'],wilderness:['历史资料记录参与保护地建设的旅行建造项目。','Source materials record a travel-building project for protected-area construction.'],'future-architects':['历史资料记录面向 8–14 岁的双语冬令营与夏令营。','Source materials record bilingual winter and summer camps for ages 8–14.']};const common={ 'digital-joinery':['数字榫卯是常识班记录的课程主题。','Digital joinery is a recorded Common Knowledge subject.'],energy:['发电是常识班记录的课程主题。','Energy generation is a recorded Common Knowledge subject.'],water:['水系统是常识班记录的课程主题。','Water systems are a recorded Common Knowledge subject.'],architecture:['建筑是常识班记录的课程主题。','Architecture is a recorded Common Knowledge subject.'],painting:['刷漆是常识班记录的课程主题。','Painting is a recorded Common Knowledge subject.'],cement:['水泥是常识班记录的课程主题。','Cement is a recorded Common Knowledge subject.'],'hardware-welding':['五金焊接是常识班记录的课程主题。','Hardware and welding are recorded Common Knowledge subjects.']};Object.assign(data.detail,descriptions,common)}
function addProductDescriptions(){productNames.forEach(id=>{const n=routes.get('shop/kits/'+id);if(n)data.detail[id]=[`${n.zh}收录于 PFS 产品资料；当前交易状态待确认。`,`${n.en} appears in PFS product records; current sale status awaits confirmation.`]})}
