const path=location.pathname.split('/').filter(Boolean);const theme=path[1]||'palazzo',view=path[2]||'home';
const A='/pfs-public-qa/assets/';
const content={drop:['阿凡提','DIY杯垫','创意时钟','动物摆件','狗獾椅子','开瓶器','三角凳','瓦猫','富柜','Swish Chair','Neubau'],courses:[['船厂 SCHOOL','Paddle · Stitch Canoe · Stripe Canoe'],['OPENBIKE',''],['Digital Furniture',''],['常识班',''],['荒野建造大师班','大角怪'],['未来建筑师','']]};
const names={palazzo:'A / PALAZZO MONTI × PFS',folkert:'B / FOLKERT GORTER × PFS',has:'C / HAS.WORKS × PFS'};
function header(){return `<header class="proto-header"><a class="brand" href="../home/"><b>PFS</b><span>Party Friend Ship<br><small>派对朋友的飞船</small></span></a><nav>${['VISIT','STAY','BUILDING','SHOP','WORK WITH US'].map((x,i)=>`<a class="${x==='BUILDING'?'active':''}" href="${x==='BUILDING'?'../building/':'#'}"><i>0${i+1}</i>${x}</a>`).join('')}</nav><button class="menu">MENU</button><span class="lang">中文 / EN</span></header>`}
function mega(){return `<section class="mega"><div class="mega-title"><span>BUILDING</span><small>建造体验 / PROGRAMME</small></div><div class="mega-photo"><img src="${A}asset-building-process.png" alt="PFS making process"></div><div class="mega-col drop"><div class="num">01</div><h2>无需预订</h2><p>NO BOOKING NEEDED</p><div class="subindex">${content.drop.map((x,i)=>`<a><i>01.${i+1}</i>${x}</a>`).join('')}</div></div><div class="mega-col booking"><div class="num">02</div><h2>需要预订</h2><p>BOOKING REQUIRED</p><div class="subindex">${content.courses.map((x,i)=>`<a><i>02.${i+1}</i>${x[0]}<small>${x[1]}</small></a>`).join('')}</div></div></section>`}
function home(){return `<main class="home"><section class="arrival"><img src="${A}hero-1.jpg" alt="PFS landscape and building"><div class="hero-copy"><small>PARTY FRIEND SHIP / ANJI</small><h1><span class="mosaic">可持续生活</span><br>更多灵感</h1><p>Sustainability Made Fun!#</p></div></section><section class="trace"><div class="trace-copy"><span>01 / PLACE</span><h2>一个仍在被建造、使用与改变的地方。</h2><p>People, spaces, objects and making coexist on the same site.</p></div><img src="${A}asset-team-work.png" alt="People working at PFS"></section><section class="programme"><header><span>02 / WHAT'S ON</span><h2>当前痕迹</h2></header><ol><li><time>09.28</time><b>建造现场记录</b><span>BUILDING / ANJI</span></li><li><time>10.03</time><b>船厂工作过程</b><span>SHIPYARD / MAKING</span></li><li><time>ONGOING</time><b>材料、工具与未完成的结构</b><span>FIELD NOTES</span></li></ol><img src="${A}archive-boat-making.jpg" alt="Boat making at PFS"></section><section class="enter"><span>03 / EXPLORE</span><h2>Spaces · Projects · Courses · Objects</h2><img src="${A}archive-xinjiang-process.jpg" alt="PFS building process"></section></main>`}
function building(){return `<main class="building"><section class="building-lead"><div><small>BUILDING / MAKING PROGRAMME</small><h1><span class="mosaic">建造</span><br>从材料到真实实践</h1><p>Learning and making happen inside building practice.</p></div><img src="${A}asset-building-process.png" alt="Building process"></section><section class="two-paths"><article><span>01</span><h2>无需预订</h2><small>NO BOOKING NEEDED</small><img src="${A}asset-shop-team.png" alt="Soft kit making"><p>${content.drop.join(' · ')}</p></article><article><span>02</span><h2>需要预订</h2><small>BOOKING REQUIRED</small><img src="${A}archive-boat-making.jpg" alt="Course making process"><p>船厂 SCHOOL · OPENBIKE · Digital Furniture · 常识班 · 荒野建造大师班 · 未来建筑师</p></article></section><section class="process"><span>PROCESS / FIELD NOTE</span><h2>Material → Tools → Hands → Assembly → Result</h2><img src="${A}asset-team-build-close.jpg" alt="Hands and tools in a real build"></section></main>`}
function mobile(){return `<main class="mobile-view">${mega()}</main>`}
document.documentElement.dataset.theme=theme;document.body.innerHTML=header()+(view==='building'?building():view==='home-building-menu'?mega()+home():view==='mobile-nav'?mobile():home())+`<aside class="prototype-tag">${names[theme]} · ${view.replaceAll('-',' ')}</aside>`;
if(view==='home-building-menu')document.body.classList.add('menu-open');if(view==='mobile-nav')document.body.classList.add('mobile-open');
